Feature/wod 2 embed web ordering journey
realifetech/android-sdk pull request #17
Opened 2021-08-18 14:10 UTC by LokmaneKrizou

2021-08-19 14:52 UTC, sjulia7 requested changes

2021-08-19 14:52 UTC, sjulia7 commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +        orderingUrlEditTextView.doOnTextChanged { text, _, _, _ ->
Can we extract this couple of lines to a separate function?

2021-08-19 14:52 UTC, sjulia7 commented on app/src/main/java/com/realifetech/sample/SampleApplication.kt
> +//  Set Colors via code
It this needed?

2021-08-19 14:52 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFeature.kt
> +object WebOrderingFeature {
<3

2021-08-19 14:52 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +            activity?.supportActionBar?.apply {
I guess the lines below are going to be used in several places with the time. Can we already create an extension function, similar to setUpToolbarWithBackButton / setUpToolbar in our platform app?

2021-08-19 14:52 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +                settings.apply {
Can we split this function into smaller ones as well? Like a different one to setupSettings() for example that is going to wrap up lines between 88 - 100?

2021-08-19 14:52 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/utils/ColorPallet.kt
> +internal object ColorPallet {
<3

2021-08-19 15:55 UTC, mickeylee25 commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +            RealifeTech.getGeneral().configuration.webOrderingJourneyUrl = text.toString()
Okay, so I will also move  `webOrderingJourneyUrl` to the configuration level in next iOS PR.

2021-08-19 15:55 UTC, mickeylee25 commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +        ordering_journey.setOnClickListener { Sell.createOrderingJourneyViewController() }
I thought Android would call it `createOrderingJourneyFragment`

2021-08-19 16:05 UTC, mickeylee25 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +                    if (isNetworkAvailable()) LOAD_DEFAULT else LOAD_CACHE_ELSE_NETWORK
Okay, I will use the similar cache policy for iOS

2021-08-20 08:08 UTC, Fabio-Insolia-LiveStyled approved these changes

2021-08-20 08:21 UTC, LokmaneKrizou commented on app/src/main/java/com/realifetech/sample/SampleApplication.kt
> +//  Set Colors via code
it shows example of how you can use colors via code

2021-08-20 08:23 UTC, LokmaneKrizou commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +            activity?.supportActionBar?.apply {
not really, at this stage we have only one view, and i am not aware if there will be more features requires views, when that time comes, i will make an extension for this one

2021-08-20 08:24 UTC, LokmaneKrizou commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +            RealifeTech.getGeneral().configuration.webOrderingJourneyUrl = text.toString()
where do you have it right now?

2021-08-20 08:27 UTC, LokmaneKrizou commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +        ordering_journey.setOnClickListener { Sell.createOrderingJourneyViewController() }
yeah, that was written in the document, but you are right, i ll change it to fragment, it does make more sense.

2021-08-20 13:22 UTC, mickeylee25 commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +            RealifeTech.getGeneral().configuration.webOrderingJourneyUrl = text.toString()
I set the URL with `RealifeTech().set(webOrderingJourneyUrl: String)` according to the document, but adding ` webOrderingJourneyUrl` to the SDK configuration and is assigned to the Sell when configuring the SDK makes more sense for me.

2021-08-20 17:03 UTC, LokmaneKrizou commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +            RealifeTech.getGeneral().configuration.webOrderingJourneyUrl = text.toString()
i see your point, Let's agree then to use Realifetech.getSell().configuration. webOrderingJourneyUrl = some text

2021-08-23 07:11 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +            activity?.supportActionBar?.apply {
ok I see, thanks!

2021-08-23 07:14 UTC, sjulia7 approved these changes

2021-08-23 09:30 UTC, mickeylee25 commented on app/src/main/java/com/realifetech/sample/MainActivity.kt
> +            RealifeTech.getGeneral().configuration.webOrderingJourneyUrl = text.toString()
Okay, I've created a function `RealifeTech().set(webOrderingJourneyUrl: String)` to match architecture though. To conclude, there are two ways of setting the web ordering journey URL to the SDK.
1. Through SDK configuration when the host app initialises the SDK.
2. Override the URL via `set(webOrderingJourneyUrl: String)` interface from the host app if they want. -> We will add the READEME as the [architecture](https://livestyled.atlassian.net/wiki/spaces/PROD/pages/2966487103/Mobile+SDK+-+Web+Ordering+Journey+Mobile+Architecture#Update-Documentation) says.

2021-08-23 09:30 UTC, mickeylee25 approved these changes

2021-08-23 10:10 UTC, Fabio-Insolia-LiveStyled approved these changes

2021-08-23 10:11 UTC, merged