Feature/wod 48 implement host app login
realifetech/android-sdk pull request #29
Opened 2021-09-27 08:20 UTC by LokmaneKrizou

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/identity/Identity.kt
> +                GlobalScope.launch(dispatcherIO) {
It's already wrapped into GlobalScope.launch(dispatcherIO) - do we need to call it again inside the callback? Why the scope doesn't persist?

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +    internal lateinit var networkUtil: NetworkUtil
Why internal?

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
>      override fun onViewStateRestored(savedInstanceState: Bundle?) {
Is there a specific reason to use here    onViewStateRestored(savedInstanceState: Bundle?)  instead of for example onViewCreated() ?

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebViewWrapper.kt
> +            cacheMode = WebSettings.LOAD_CACHE_ELSE_NETWORK
Should we check the reversed condition and remove the cacheMode assignment if the network is available, or this case is not valid?

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebViewWrapper.kt
> +                    visibility = View.VISIBLE
How about isVisible = true (minor thing)

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebViewWrapper.kt
> +        private const val DEEP_LINK="rlthostapplogin"
Is this always going to be called rlthostapplogin , for all clients?

2021-09-28 11:14 UTC, sjulia7 commented on sdk/src/test/java/com/realifetech/sdk/core/utils/StringExtensionsKtTest.kt
> +class StringExtensionsKtTest {
<3

2021-09-28 13:41 UTC, Fabio-Insolia-LiveStyled requested changes

2021-09-28 13:41 UTC, Fabio-Insolia-LiveStyled commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
>      override fun onViewStateRestored(savedInstanceState: Bundle?) {
Maybe because there is the chance to have to come back from another activity/fragment

2021-09-28 13:41 UTC, Fabio-Insolia-LiveStyled commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebViewWrapper.kt
> +        private const val DEEP_LINK="rlthostapplogin"
as far as I know from my convo with Ross yes ... otherwise we still don't have a tool to provide this value customised per client

2021-09-28 13:41 UTC, Fabio-Insolia-LiveStyled commented on sdk/src/test/java/com/realifetech/sdk/identity/mocks/IdentityMocks.kt
> +        "test@gmail.com","Fabio".toInput(), "BigOnion".toInput(), Input.absent(),
![IMG-20210911-WA0000](https://user-images.githubusercontent.com/48317428/135097993-9e271cf6-72e2-407f-938c-4abb0fa23325.jpg)

2021-09-28 13:41 UTC, Fabio-Insolia-LiveStyled commented on app/src/main/AndroidManifest.xml
> -        android:networkSecurityConfig="@xml/network_security_config"
Did we removed the network_security_config file?

2021-09-28 13:41 UTC, Fabio-Insolia-LiveStyled commented on app/src/main/java/com/realifetech/sample/identity/IdentityActivity.kt
> +import kotlinx.android.synthetic.main.activity_identity.*
+1 ... let's use the binding as we already do in the main app

2021-09-28 14:26 UTC, LokmaneKrizou commented on app/src/main/java/com/realifetech/sample/identity/IdentityActivity.kt
> +import kotlinx.android.synthetic.main.activity_identity.*
sure i will make the change, however  i wouldn't worry as this is the sample app,
meanwhile i already made sure to use binding in the web ordering journey fragment

2021-09-28 14:27 UTC, LokmaneKrizou commented on sdk/src/main/java/com/realifetech/sdk/core/data/database/preferences/auth/AuthTokenStorage.kt
> +                Log.e(this.javaClass.name, "Couldn't get AuthToken: %s", e)
i will create a ticket for that.

2021-09-28 14:44 UTC, LokmaneKrizou commented on sdk/src/main/java/com/realifetech/sdk/sell/weboredering/WebOrderingFragment.kt
> +    internal lateinit var networkUtil: NetworkUtil
this is not something the client will need and its mainly used inside the SDK, so i thought maybe we should make it internal

2021-09-28 14:50 UTC, LokmaneKrizou commented on app/src/main/AndroidManifest.xml
> -        android:networkSecurityConfig="@xml/network_security_config"
not entirely , i needed to exclude it so i can use my local react app since it is running on http protocol. and this networkSecurityConfig keep blocking it, i will return this line once we have webbylab app ready

2021-09-28 15:05 UTC, LokmaneKrizou commented on app/src/main/java/com/realifetech/sample/utils/RxExtensions.kt
> +fun addSubscription(disposable: Disposable?, compositeDisposable: CompositeDisposable) {
i was doing some stupid stuff in the sample app, and forget to remove it, thanks !

2021-09-28 17:01 UTC, LokmaneKrizou commented on sdk/src/main/java/com/realifetech/sdk/identity/Identity.kt
> +                GlobalScope.launch(dispatcherIO) {
the callback doesn't know about the first GlobalScope, this is what i got when i tried run it directly without the second GlobalScope, it seems that the callback isn't inside the coroutine body.
<img width="655" alt="Screenshot 2021-09-28 at 17 59 27" src="https://user-images.githubusercontent.com/19841948/135132253-da684cd0-9108-4886-8617-f13a171a9968.png">

2021-09-29 10:24 UTC, sjulia7 approved these changes

2021-09-29 14:28 UTC, Fabio-Insolia-LiveStyled approved these changes

2022-02-02 09:11 UTC, Fabio-Insolia-LiveStyled approved these changes

2022-02-02 09:58 UTC, merged